---
title: "002-Minimum Working Example"
author: "by Sahir Bhatnagar"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    theme: flatly
    highlight: tango
    fig_caption: yes
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
bibliography: 002-bibliography.bib
link-citations: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(knitr, here) # needed for filepaths

# can set global options here
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# you can create custom chunk options
knitr::opts_template$set(
  fig.large = list(fig.width = 7, fig.height = 5, fig.align = 'center', fig.pos = 'h'),
  fig.small = list(fig.width = 6, fig.height = 4, fig.align = 'center', fig.pos = 'h'),
  fig.full = list(fig.width = 8, fig.height = 6, fig.align = 'center', fig.pos = 'h')
)


# read in scripts. Note: this will not run the code. 
# Like a 'promise'
knitr::read_chunk(here::here("R","002-packages.R"))
```


```{r required-packages, results = 'hide'}
```


# Introduction

We familiarize ourselves with the basics of `knitr` [@k1;@k2;@k3]; including plots, tables and code. 


<br>


# Figures

The first example is given by \@ref(fig:fig1)

```{r fig1, fig.cap='Random noise histogram'}
par(mar=c(4,4,.1,.1))
x = rnorm(100)
hist(x, main= "", col = "lightblue", border = "white")
rug(x)
```


```{r}
plot(cars, pch=20, col='darkgray')
fit <- lm(dist ~ speed, data=cars)
abline(fit, lwd = 2)
```

```{r}
par(mfrow=c(2,2))
plot(fit)
```



# Tables

```{r}
knitr::kable(cars)
```


<br>



# Code {-}

```{r all-code, ref.label=knitr::all_labels(), echo = TRUE, eval = FALSE}
```

# Session Information

```{r}
print(sessionInfo(), locale = FALSE)
```


# References

