---
title: "007-Sensitivity Analysis of Many Paramters"
author: "Clustering Gene Expression Data"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    theme: flatly
    keep_md: yes
    highlight: tango
    fig_caption: yes
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
bibliography: 006-bibliography.bib
link-citations: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(knitr, here) # needed for filepaths

options(width=60, digits=2)
set.seed(45)
opts_chunk$set(echo = FALSE, tidy = TRUE, cache = FALSE, warning = FALSE, message = FALSE)
opts_template$set(
    fig.large = list(fig.width = 7, fig.height = 5, fig.align = 'center', fig.pos = 'H'),
    fig.small = list(fig.width = 6, fig.height = 4, fig.align = 'center', fig.pos = 'H'),
    fig.full = list(fig.width = 8, fig.height = 6, fig.align = 'center', fig.pos = 'H')
)
opts_knit$set(eval.after = 'fig.cap') # for captions to be evaluated after R objects are available 

knitr::read_chunk(here::here("R","007-packages.R"))
```


```{r required-packages, results = 'hide'}
```





<br>


# Code {-}

```{r all-code, ref.label=knitr::all_labels(), echo = TRUE, eval = FALSE}
```

# Session Information

```{r}
print(sessionInfo(), locale = FALSE)
```


# References

